// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njzmgqbqzzakzbjprdbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qem1ncWJxenpha3pianByZGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjExODAsImV4cCI6MjA3MDQ5NzE4MH0.4ADWO4RZSnzS1fbitasFYJxc-a3Dzb-EBXLcqBYePgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});